name: Run Notebooks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
    

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert ipython[all]
    - name: Execute notebooks
      run: python -m nbconvert --execute --to notebook ./notebooks/Theoretical_LVR.ipynb

  job2:
    runs-on: ubuntu-latest
    needs: job1

    strategy:
      matrix:
        file: ["./notebooks/LVR_Comparison_LQTYETH.ipynb", "./notebooks/LVR_Comparison_USDCETH.ipynb"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert ipython[all]
    - name: Execute notebooks
      run: python -m nbconvert --execute --to notebook ${{ matrix.file }}